services:
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start
      network_mode: bridge
      environment:
        KC_HOSTNAME: localhost
        KC_HOSTNAME_PORT: 8080
        KC_HOSTNAME_STRICT_BACKCHANNEL: false
        KC_HTTP_ENABLED: true
        KC_HOSTNAME_STRICT_HTTPS: false
        KC_HEALTH_ENABLED: true
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      ports:
        - 8080:8080